services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - server
    volumes:
      - ./app:/var/www/findthebeat
      - /var/www/findthebeat/nodes_modules
      - /var/www/findthebeat/vendor
      - /var/www/findthebeat/var



networks:
  server:
    driver: bridge