<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220714220012 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_D5F9069C1A4A6FFA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__beat AS SELECT id, m20, m19, m18, m17, m16, m15, m14, m13, m12, m11, m10, m9, m8, m7, m6, m5, m4, m3, m2, m1, current_beat, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20 FROM beat');
        $this->addSql('DROP TABLE beat');
        $this->addSql('CREATE TABLE beat (id INTEGER NOT NULL, m20 DOUBLE PRECISION DEFAULT NULL, m19 DOUBLE PRECISION DEFAULT NULL, m18 DOUBLE PRECISION DEFAULT NULL, m17 DOUBLE PRECISION DEFAULT NULL, m16 DOUBLE PRECISION DEFAULT NULL, m15 DOUBLE PRECISION DEFAULT NULL, m14 DOUBLE PRECISION DEFAULT NULL, m13 DOUBLE PRECISION DEFAULT NULL, m12 DOUBLE PRECISION DEFAULT NULL, m11 DOUBLE PRECISION DEFAULT NULL, m10 DOUBLE PRECISION DEFAULT NULL, m9 DOUBLE PRECISION DEFAULT NULL, m8 DOUBLE PRECISION DEFAULT NULL, m7 DOUBLE PRECISION DEFAULT NULL, m6 DOUBLE PRECISION DEFAULT NULL, m5 DOUBLE PRECISION DEFAULT NULL, m4 DOUBLE PRECISION DEFAULT NULL, m3 DOUBLE PRECISION DEFAULT NULL, m2 DOUBLE PRECISION DEFAULT NULL, m1 DOUBLE PRECISION DEFAULT NULL, current_beat INTEGER NOT NULL, p1 DOUBLE PRECISION DEFAULT NULL, p2 DOUBLE PRECISION DEFAULT NULL, p3 DOUBLE PRECISION DEFAULT NULL, p4 DOUBLE PRECISION DEFAULT NULL, p5 DOUBLE PRECISION DEFAULT NULL, p6 DOUBLE PRECISION DEFAULT NULL, p7 DOUBLE PRECISION DEFAULT NULL, p8 DOUBLE PRECISION DEFAULT NULL, p9 DOUBLE PRECISION DEFAULT NULL, p10 DOUBLE PRECISION DEFAULT NULL, p11 DOUBLE PRECISION DEFAULT NULL, p12 DOUBLE PRECISION DEFAULT NULL, p13 DOUBLE PRECISION DEFAULT NULL, p14 DOUBLE PRECISION DEFAULT NULL, p15 DOUBLE PRECISION DEFAULT NULL, p16 DOUBLE PRECISION DEFAULT NULL, p17 DOUBLE PRECISION DEFAULT NULL, p18 DOUBLE PRECISION DEFAULT NULL, p19 DOUBLE PRECISION DEFAULT NULL, p20 DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('INSERT INTO beat (id, m20, m19, m18, m17, m16, m15, m14, m13, m12, m11, m10, m9, m8, m7, m6, m5, m4, m3, m2, m1, current_beat, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20) SELECT id, m20, m19, m18, m17, m16, m15, m14, m13, m12, m11, m10, m9, m8, m7, m6, m5, m4, m3, m2, m1, current_beat, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20 FROM __temp__beat');
        $this->addSql('DROP TABLE __temp__beat');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5F9069C1A4A6FFA ON beat (current_beat)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX UNIQ_D5F9069C1A4A6FFA');
        $this->addSql('CREATE TEMPORARY TABLE __temp__beat AS SELECT id, m20, m19, m18, m17, m16, m15, m14, m13, m12, m11, m10, m9, m8, m7, m6, m5, m4, m3, m2, m1, current_beat, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20 FROM beat');
        $this->addSql('DROP TABLE beat');
        $this->addSql('CREATE TABLE beat (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, m20 DOUBLE PRECISION DEFAULT NULL, m19 DOUBLE PRECISION DEFAULT NULL, m18 DOUBLE PRECISION DEFAULT NULL, m17 DOUBLE PRECISION DEFAULT NULL, m16 DOUBLE PRECISION DEFAULT NULL, m15 DOUBLE PRECISION DEFAULT NULL, m14 DOUBLE PRECISION DEFAULT NULL, m13 DOUBLE PRECISION DEFAULT NULL, m12 DOUBLE PRECISION DEFAULT NULL, m11 DOUBLE PRECISION DEFAULT NULL, m10 DOUBLE PRECISION DEFAULT NULL, m9 DOUBLE PRECISION DEFAULT NULL, m8 DOUBLE PRECISION DEFAULT NULL, m7 DOUBLE PRECISION DEFAULT NULL, m6 DOUBLE PRECISION DEFAULT NULL, m5 DOUBLE PRECISION DEFAULT NULL, m4 DOUBLE PRECISION DEFAULT NULL, m3 DOUBLE PRECISION DEFAULT NULL, m2 DOUBLE PRECISION DEFAULT NULL, m1 DOUBLE PRECISION DEFAULT NULL, current_beat INTEGER NOT NULL, p1 DOUBLE PRECISION DEFAULT NULL, p2 DOUBLE PRECISION DEFAULT NULL, p3 DOUBLE PRECISION DEFAULT NULL, p4 DOUBLE PRECISION DEFAULT NULL, p5 DOUBLE PRECISION DEFAULT NULL, p6 DOUBLE PRECISION DEFAULT NULL, p7 DOUBLE PRECISION DEFAULT NULL, p8 DOUBLE PRECISION DEFAULT NULL, p9 DOUBLE PRECISION DEFAULT NULL, p10 DOUBLE PRECISION DEFAULT NULL, p11 DOUBLE PRECISION DEFAULT NULL, p12 DOUBLE PRECISION DEFAULT NULL, p13 DOUBLE PRECISION DEFAULT NULL, p14 DOUBLE PRECISION DEFAULT NULL, p15 DOUBLE PRECISION DEFAULT NULL, p16 DOUBLE PRECISION DEFAULT NULL, p17 DOUBLE PRECISION DEFAULT NULL, p18 DOUBLE PRECISION DEFAULT NULL, p19 DOUBLE PRECISION DEFAULT NULL, p20 DOUBLE PRECISION DEFAULT NULL)');
        $this->addSql('INSERT INTO beat (id, m20, m19, m18, m17, m16, m15, m14, m13, m12, m11, m10, m9, m8, m7, m6, m5, m4, m3, m2, m1, current_beat, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20) SELECT id, m20, m19, m18, m17, m16, m15, m14, m13, m12, m11, m10, m9, m8, m7, m6, m5, m4, m3, m2, m1, current_beat, p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20 FROM __temp__beat');
        $this->addSql('DROP TABLE __temp__beat');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D5F9069C1A4A6FFA ON beat (current_beat)');
    }
}
