services:
  server:
    build:
      context: .
      dockerfile: apache.Dockerfile
    ports:
      - 80:80
    networks:
      - server

  phpfpm:
    build:
      context: .
      dockerfile: php.Dockerfile
    expose:
      - 9000
    networks:
      - server


networks:
  server:
    driver: bridge